name: ZAP DAST Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_baseline:
    runs-on: ubuntu-20.04
    steps:
      - name: Pull OWASP ZAP Docker Image
        run: docker pull zaproxy/zap-stable

      - name: Run OWASP ZAP Baseline Scan
        run: |
          TARGET_URL="https://coride.site"
          docker run --user root --rm -v $(pwd):/zap/wrk:rw -w /zap zaproxy/zap-stable zap-baseline.py \
            -t $TARGET_URL \
            -J zap-output.json \
            -r zap-report.html \
            -d \
            -m 5 \
            -I || true

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: ZAP Reports
          path: |
            zap-output.json
            zap-report.html
        if: always()

      - name: Display ZAP Scan Results
        run: |
          echo "Resumen del escaneo en formato JSON:"
          cat zap-output.json | jq '.'
          echo "Fin del reporte."

      - name: Analyze Exit Code
        run: |
          TARGET_URL="https://coride.site"
          docker run --user root --rm -v $(pwd):/zap/wrk:rw -w /zap zaproxy/zap-stable zap-baseline.py \
            -t $TARGET_URL \
            -J zap-output.json \
            -r zap-report.html \
            -d \
            -m 5
          EXIT_CODE=$?

          if [ $EXIT_CODE -eq 2 ]; then
              echo "Advertencias detectadas, pero continuando el pipeline."
          elif [ $EXIT_CODE -ne 0 ]; then
              echo "Error crítico detectado. Deteniendo pipeline."
              exit $EXIT_CODE
          fi
