zap_baseline:
  runs-on: ubuntu-20.04
  needs: analyze
  steps:
    - name: Pull OWASP ZAP Docker Image
      run: docker pull zaproxy/zap-stable

    - name: Run OWASP ZAP Baseline Scan
      run: |
        TARGET_URL="${{ secrets.TARGET_URL }}"
        docker run --user root --rm -v $(pwd):/zap/wrk:rw -w /zap zaproxy/zap-stable zap-baseline.py \
          -t $TARGET_URL \
          -J zap-output.json \
          -r zap-report.html \
          --autoexit \
          -config api.disablekey=true

    - name: Upload ZAP Reports
      uses: actions/upload-artifact@v4
      with:
        name: ZAP Reports
        path: |
          zap-output.json
          zap-report.html
      if: always()

    - name: Display Scan Results in Logs
      run: |
        echo "Resumen del escaneo:"
        jq '.' zap-output.json
